<!-- Code to extend the base layout -->
@extends('layout')
<!-- Code to add the content in section content-left -->
@section('content-left')
   <h4>About Us page content - !!!!!</h4>     
      Let Us Rise Up and Be Thankful…
      For If We Did Not Learn a Lot Today…
	  At Least We Learned a Little…
	  And If We Did Not Learn a Little…
      At Least We Did Not Get Sick…
      And If We Got Sick…
      At Least We Did Not Die…
      So Let Us All Be Thankful… ”
@stop
